###############################################################################
###############################################################################
#-----------------------------------------------------------------------------#
####Author     : Kelli Faye Johnson
####Contact    : kellifayejohnson@gmail.com
####Lastupdate : 2015-01-08
####Purpose    : To create casefiles for ss3sim
####Packages   : ss3sim
####Inputs     :
####Outputs    :
####Remarks    : Character width = 80
#-----------------------------------------------------------------------------#
###############################################################################
###############################################################################

###############################################################################
###############################################################################
#### Step
#### Make sure dependent objects are available
###############################################################################
###############################################################################
neededobjects <- c("case_folder", "my.forecasts", "my.spp")

ignore <- sapply(neededobjects, function(x) {
    if (!exists(x)) {
    stop(paste0("\n\n Error message from KFJ:\n",
                "AR_generateCaseFiles.R should be called from the script",
                "AR_Simulations_KFJ.R.\n",
                "\"", x, "\" is part of AR_Simulations_KFJ.R, and was not found."))
}
})

writeF <- function(start = 1, end = 100, fvals, species, case,
                   comment = "# Casefile autogenerated using create_f.R") {
    sink(paste0("F", case, "-", species, ".txt"))
    on.exit(sink())
    cat(comment)
    cat("years; c(", paste(start:end, collapse = ", "), ")\n",
        "years_alter; c(", paste(start:end, collapse = ", "), ")\n",
        "fvals; c(", paste(fvals, collapse = ", "), ")\n", sep = "")
}

###############################################################################
###############################################################################
#### Step
#### Generate case files
###############################################################################
###############################################################################
if (!file.exists(case_folder)) {
  stop(paste("The casefile folder,", case_folder, " does not exist."))
}
wd.entry <- getwd()
setwd(case_folder)

start <- 1

start.survey  <- start + burnin + 15
start.fishery <- start + burnin
freq.survey  <- 2
freq.fishery <- 2
years.fish <- nyears + start - start.fishery - my.forecasts
years.surv <- nyears + start - start.survey - my.forecasts
all.fish <- seq(start.fishery, start.fishery + years.fish - 1, by = freq.fishery)
all.surv <- seq(start.survey, start.survey + years.surv - 1, by = freq.survey)

# F
tofind <- paste0("F[0]+-", my.spp)
ffiles <- sapply(tofind, grep, value = TRUE,
  x = list.files(system.file("cases", package = "ss3models"), full.names = TRUE))
done <- file.copy(ffiles, ".", recursive = TRUE, overwrite = TRUE)
if (!any(done)) {
    stop(paste("Fishing case files were not properly copied."))
}
for (spp in my.spp) {
  fmsy <- ss3sim:::get_args(paste0("F0-", spp, ".txt"))$fvals
  fmsy <- unique(fmsy[fmsy != 0])
  writeF(fvals =
    c(rep(0, burnin), rep(fmsy, years.fish), rep(0, my.forecasts)),
    species = spp, case = 1,
    comment = "# No fishing during forecast\n", start = start, end = nyears)
}

# Years of survey index of abundance
case_index(fleets = 2,
  years = list(all.surv), sd = list(my.dats[3]), case = 0, spp = my.spp)

# Age comp
# Low data with fishery and survey and dirichlet
case_comp(fleets = 1:2,
  Nsamp = list(rep(my.dats[1], length(all.fish)), rep(my.dats[1], length(all.surv))),
  years = list(all.fish, all.surv), cpar = 2:1,
  type = "agecomp", case = my.dats[1], spp = my.spp)
case_comp(fleets = 1:2,
  Nsamp = list(rep(my.dats[2], length(all.fish)), rep(my.dats[2], length(all.surv))),
  years = list(all.fish, all.surv), cpar = 2:1,
  type = "agecomp", case = my.dats[2], spp = my.spp)
case_comp(fleets = 1:2,
  Nsamp = list(rep(my.dats[4], length(all.fish)), rep(my.dats[4], length(all.surv))),
  years = list(all.fish, all.surv), cpar = 2:1,
  type = "agecomp", case = my.dats[4], spp = my.spp)

# Length comp
case_comp(fleets = 1:2,
  Nsamp = list(rep(my.dats[1], length(all.fish)), rep(my.dats[1], length(all.surv))),
  years = list(all.fish, all.surv), cpar = 2:1,
  type = "lcomp", case = my.dats[1], spp = my.spp)
case_comp(fleets = 1:2,
  Nsamp = list(rep(my.dats[2], length(all.fish)), rep(my.dats[2], length(all.surv))),
  years = list(all.fish, all.surv), cpar = 2:1,
  type = "lcomp", case = my.dats[2], spp = my.spp)
case_comp(fleets = NULL, Nsamp = NULL, years = NULL, cpar = 1,
  type = "lcomp", case = 0, spp = my.spp)

## Generate casefiles for different lengths of forecasting using E
for (f in 1:length(my.forecasts)){
    file.current <- paste0("E", my.forecasts[f], "-", my.spp, ".txt")
    mapply(writeLines, con = file.current, MoreArgs = list(c(
    "# description: Fixed M, no qSurvey, w a given forecast number",
    "natM_type; 1Parm",
    "natM_n_breakpoints; NULL",
    "natM_lorenzen; NULL",
    "natM_val; c(NA, -1)",
    "par_name; NULL",
    "par_int; NA",
    "par_phase; NULL",
    paste("forecast_num;", my.forecasts)))
    )
}
# Each forecast length but turn growth off
for (f in 1:length(my.forecasts)){
    file.current <- paste0("E1", my.forecasts[f], "-", my.spp, ".txt")
    mapply(writeLines, con = file.current, MoreArgs = list(c(
    "# description: Fixed M, no qSurvey, w a given forecast number",
    "natM_type; 1Parm",
    "natM_n_breakpoints; NULL",
    "natM_lorenzen; NULL",
    "natM_val; c(NA, -1)",
    "par_name; c(\"L_at_Amin_Fem_GP_1\", \"L_at_Amax_Fem_GP_1\",\"VonBert_K_Fem_GP_1\", \"CV_young_Fem_GP_1\", \"CV_old_Fem_GP_1\")",
    "par_int; NA",
    "par_phase; rep(-1, 5)",
    paste("forecast_num;", my.forecasts)))
    )
}

setwd(wd.entry)
rm("wd.entry")
