\documentclass{article}
\usepackage[T1]{fontenc}

\begin{document}
A single scenario with 100 iterations was ran for cod, where
there are 2000 age- and length-compositions per sampling year
for both the fishery and the survey.
The coefficient of variation for the survey index of abundance
was decreased from 0.2 to 0.1 and the number of years was increased.
Note that the survey is still not available every year, nor is
composition data.

<<setup, include=FALSE>>=
options(xtable.comment = FALSE)
@

<<echo = FALSE>>=
library(ss3sim)
library(xtable)
scalars <- read.csv("ss3sim_scalar.csv", header = TRUE)
ts <- read.csv("ss3sim_ts.csv", header = TRUE)
scalars <- calculate_re(scalars, TRUE)

ts$SSB_re <- with(ts, ((SpawnBio_om - SpawnBio_em) / SpawnBio_om))
ts$R0_re <- with(ts, ((Recruit_0_om - Recruit_0_em) / Recruit_0_om))
ts$F_re <- with(ts, ((F_om - F_em) / F_om))
@

<<echo = FALSE, fig.height = 8>>=
par(mfrow = c(3, 1), mar = c(0, 5, 0, 1), oma = c(4, 1, 2, 2),
  tck = -0.001, mgp = c(2.75, 0.15, 0))
for (par in c("SSB_re", "R0_re", "F_re")) {
x <- aggregate(eval(parse(text = par)) ~ year, data = ts, mean)
plot(x, ylim = c(-max(abs(x[, 2])), max(abs(x[, 2]))), las = 1,
  ylab = par, xaxt = "n")
abline(h = 0, lty = 2, col = "red")
  if (par == "SSB_re") {
    legend("topright", legend = "legend reveals years with data", bty = "n")
    x <- ss3sim:::get_args(file.path("..", "cases", "index100-cod.txt"))$years[[1]]
    points(x, rep(par("yaxp")[2] * 1.15, length(x)))
    text(-4, rep(par("yaxp")[2]) * 1.15, "survey (CV=0.1)", pos = 4)

    x <- ss3sim:::get_args(file.path("..", "cases", "lcomp100-cod.txt"))$years[[2]]
    points(x, rep(par("yaxp")[2], length(x)))
    text(-4, rep(par("yaxp")[2]), "survey comp (n=2000)", pos = 4)

    x <- ss3sim:::get_args(file.path("..", "cases", "lcomp100-cod.txt"))$years[[1]]
    points(x, rep(par("yaxp")[2] * 0.85, length(x)))
    text(-4, rep(par("yaxp")[2]) * 0.85, "fish comp (n=2000)", pos = 4)
  }
}
  axis(1)
  mtext(side = 1, outer = TRUE, "years", line = 2)
  legend("bottomright", legend = "*note scales are different but symmetrical",
    bty = "n")
  mtext(side = 3, outer = TRUE,
    "Relative error of cod with large samples sizes and bias adjustment")
@

<<echo = FALSE>>=
temp <- list()
counter <- 1
mynames <- grep("_re", names(scalars), value = TRUE)[c(3,4,7:11,22,32,34,38,40)]
for(ind in mynames) {
  if (!all(is.numeric(eval(parse(text = paste0("scalars[,\"", ind, "\"]")))))) next
  temp[[counter]] <- aggregate(eval(parse(text = ind)) ~ species, data = scalars, mean, na.rm = FALSE)
  counter <- counter + 1
}
temp <- do.call("rbind", sapply(temp, "[", 2))
rownames(temp) <- mynames
@

<<echo = FALSE, results = 'asis'>>=
print(xtable(temp, digits = 5,
  caption = "Relative error in estimated parameters."), include.rownames = TRUE,
  include.colnames = FALSE,
  )
@

\end{document}
